import AppKit
import SwiftUI

/// Recent text copied anywhere on the Mac. Kept in memory only; entries that password
/// managers mark as concealed or transient are never recorded.
@MainActor
final class ClipboardHistory: ObservableObject {
    struct Item: Identifiable, Equatable {
        let id = UUID()
        let text: String
        let date: Date
    }

    @Published private(set) var items: [Item] = []
    /// Strips tracking parameters from a copied link and puts the clean link back on the pasteboard.
    var cleansLinks = false

    private let pasteboard: NSPasteboard
    private var lastChange: Int
    private var timer: Timer?
    private static let limit = 50
    private static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword",
    ]

    init(pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
        lastChange = pasteboard.changeCount
    }

    func start() {
        guard timer == nil else { return }
        lastChange = pasteboard.changeCount
        timer = Timer.scheduledTimer(withTimeInterval: 0.6, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.check() }
        }
        timer?.tolerance = 0.06
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        items.removeAll()
    }

    func check() {
        guard pasteboard.changeCount != lastChange else { return }
        lastChange = pasteboard.changeCount
        let types = Set(pasteboard.types?.map(\.rawValue) ?? [])
        guard types.isDisjoint(with: Self.ignoredTypes),
              var text = pasteboard.string(forType: .string)?.trimmingCharacters(in: .whitespacesAndNewlines),
              !text.isEmpty else { return }
        if cleansLinks, let cleaned = LinkCleaner.clean(text), let items = pasteboard.pasteboardItems, items.count == 1 {
            // Keep every other flavour (link title, image, rich text); only the text and URL change.
            let copy = NSPasteboardItem()
            for type in items[0].types {
                if type == .string || type == .URL {
                    copy.setString(cleaned, forType: type)
                } else if let data = items[0].data(forType: type) {
                    copy.setData(data, forType: type)
                }
            }
            pasteboard.clearContents()
            pasteboard.writeObjects([copy])
            // Our own write must not count as a new copy.
            lastChange = pasteboard.changeCount
            text = cleaned
        }
        items.removeAll { $0.text == text }
        items.insert(Item(text: text, date: .now), at: 0)
        if items.count > Self.limit { items.removeLast(items.count - Self.limit) }
    }

    func copy(_ item: Item) {
        pasteboard.clearContents()
        pasteboard.setString(item.text, forType: .string)
        lastChange = pasteboard.changeCount
        items.removeAll { $0.id == item.id }
        items.insert(Item(text: item.text, date: .now), at: 0)
    }

    func remove(_ item: Item) { items.removeAll { $0.id == item.id } }
    func clear() { items.removeAll() }
}

struct ClipboardTab: View {
    @ObservedObject var history: ClipboardHistory
    @State private var query = ""
    @State private var copiedID: UUID?

    private var filtered: [ClipboardHistory.Item] {
        query.isEmpty ? history.items : history.items.filter { $0.text.localizedCaseInsensitiveContains(query) }
    }

    var body: some View {
        VStack(spacing: 8) {
            HStack(spacing: 8) {
                HStack(spacing: 6) {
                    Image(systemName: "magnifyingglass").font(.system(size: 11)).foregroundStyle(.white.opacity(0.5))
                    TextField("Search clipboard", text: $query)
                        .textFieldStyle(.plain)
                        .font(.system(size: 12))
                }
                .padding(.horizontal, 10).frame(height: 26)
                .surface(Capsule(), opacity: 0.08)
                Button("Clear") { history.clear() }
                    .buttonStyle(.plain)
                    .font(.system(size: 11, weight: .semibold))
                    .foregroundStyle(.white.opacity(history.items.isEmpty ? 0.3 : 0.7))
                    .disabled(history.items.isEmpty)
            }
            if filtered.isEmpty {
                Text(history.items.isEmpty ? String(localized: "Copied text shows up here") : String(localized: "No matches"))
                    .font(.system(size: 12)).foregroundStyle(.white.opacity(0.45))
                    .frame(maxWidth: .infinity, maxHeight: .infinity)
            } else {
                ScrollView(.vertical, showsIndicators: false) {
                    LazyVStack(spacing: 4) {
                        ForEach(filtered) { item in
                            ClipRow(item: item, copied: copiedID == item.id) {
                                history.copy(item)
                                copiedID = item.id
                                DispatchQueue.main.asyncAfter(deadline: .now() + 1.2) { if copiedID == item.id { copiedID = nil } }
                            } onRemove: { history.remove(item) }
                        }
                    }
                }
            }
        }
        .foregroundStyle(.white)
    }
}

private struct ClipRow: View {
    let item: ClipboardHistory.Item
    let copied: Bool
    let onCopy: () -> Void
    let onRemove: () -> Void
    @State private var hovering = false

    var body: some View {
        HStack(spacing: 8) {
            Text(item.text)
                .font(.system(size: 12))
                .lineLimit(2)
                .frame(maxWidth: .infinity, alignment: .leading)
            if copied {
                Image(systemName: "checkmark").font(.system(size: 11, weight: .bold)).foregroundStyle(.green)
            } else if hovering {
                Button(action: onRemove) { Image(systemName: "xmark").font(.system(size: 10, weight: .semibold)) }
                    .buttonStyle(.plain).foregroundStyle(.white.opacity(0.6))
            } else {
                Text(item.date, style: .relative).font(.system(size: 9)).foregroundStyle(.white.opacity(0.35))
            }
        }
        .padding(.horizontal, 10).padding(.vertical, 6)
        .background(RoundedRectangle(cornerRadius: 9).fill(.white.opacity(hovering ? 0.12 : 0.05)))
        .contentShape(Rectangle())
        .onTapGesture(perform: onCopy)
        .onHover { hovering = $0 }
        .help(Text("Click to copy"))
    }
}
