import AppKit
import Testing
@testable import Nunsseop

@MainActor
struct ClipboardHistoryTests {
    /// A pasteboard of its own, so the real clipboard is never read or written.
    private func fixture() -> (history: ClipboardHistory, board: NSPasteboard) {
        let board = NSPasteboard(name: NSPasteboard.Name("nunsseop-test-\(UUID().uuidString)"))
        return (ClipboardHistory(pasteboard: board), board)
    }

    private func copy(_ text: String, as extraTypes: [String] = [], to board: NSPasteboard) {
        board.clearContents()
        board.setString(text, forType: .string)
        for type in extraTypes { board.setString("x", forType: NSPasteboard.PasteboardType(type)) }
    }

    @Test(arguments: [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword",
    ])
    func textFromPasswordManagersIsNeverRecorded(type: String) {
        let (history, board) = fixture()
        defer { board.releaseGlobally() }
        copy("hunter2", as: [type], to: board)
        history.check()
        #expect(history.items.isEmpty)
    }

    @Test func plainCopiesAreRecordedNewestFirst() {
        let (history, board) = fixture()
        defer { board.releaseGlobally() }
        copy("a", to: board)
        history.check()
        copy("b", to: board)
        history.check()
        #expect(history.items.map(\.text) == ["b", "a"])
    }

    @Test func copyingTheSameTextAgainMovesItToTheTop() {
        let (history, board) = fixture()
        defer { board.releaseGlobally() }
        for text in ["a", "b", "a"] {
            copy(text, to: board)
            history.check()
        }
        #expect(history.items.map(\.text) == ["a", "b"])
    }

    @Test func checkingWithoutANewCopyAddsNothing() {
        let (history, board) = fixture()
        defer { board.releaseGlobally() }
        copy("a", to: board)
        history.check()
        history.check()
        #expect(history.items.map(\.text) == ["a"])
    }

    @Test func keepsOnlyTheFiftyNewest() {
        let (history, board) = fixture()
        defer { board.releaseGlobally() }
        for number in 0..<60 {
            copy("item \(number)", to: board)
            history.check()
        }
        #expect(history.items.count == 50)
        #expect(history.items.first?.text == "item 59")
        #expect(history.items.last?.text == "item 10")
    }

    @Test func textIsTrimmedAndBlankCopiesAreIgnored() {
        let (history, board) = fixture()
        defer { board.releaseGlobally() }
        copy("  hi\n", to: board)
        history.check()
        copy(" \n\t ", to: board)
        history.check()
        #expect(history.items.map(\.text) == ["hi"])
    }

    @Test func trackingParametersAreStrippedFromACopiedLinkAndWrittenBack() {
        let (history, board) = fixture()
        defer { board.releaseGlobally() }
        history.cleansLinks = true
        copy("https://x.com/a?utm_source=1&id=2", as: ["public.url-name"], to: board)
        history.check()
        #expect(history.items.map(\.text) == ["https://x.com/a?id=2"])
        #expect(board.string(forType: .string) == "https://x.com/a?id=2")
        #expect(board.string(forType: NSPasteboard.PasteboardType("public.url-name")) == "x")
        // The rewrite is our own, so it must not be recorded as a second copy.
        history.check()
        #expect(history.items.count == 1)
    }

    @Test func linksAreLeftAloneUnlessCleaningIsOn() {
        let (history, board) = fixture()
        defer { board.releaseGlobally() }
        copy("https://x.com/a?utm_source=1&id=2", to: board)
        history.check()
        #expect(history.items.map(\.text) == ["https://x.com/a?utm_source=1&id=2"])
        #expect(board.string(forType: .string) == "https://x.com/a?utm_source=1&id=2")
    }

    @Test func copyingAnEntryBackMovesItToTheTopWithoutDuplicating() throws {
        let (history, board) = fixture()
        defer { board.releaseGlobally() }
        for text in ["a", "b", "c"] {
            copy(text, to: board)
            history.check()
        }
        history.copy(try #require(history.items.last))
        #expect(history.items.map(\.text) == ["a", "c", "b"])
        #expect(board.string(forType: .string) == "a")
        history.check()
        #expect(history.items.map(\.text) == ["a", "c", "b"])
    }

    @Test func removeClearAndStopEmptyTheList() throws {
        let (history, board) = fixture()
        defer { board.releaseGlobally() }
        for text in ["a", "b", "c"] {
            copy(text, to: board)
            history.check()
        }
        history.remove(try #require(history.items.first { $0.text == "b" }))
        #expect(history.items.map(\.text) == ["c", "a"])
        history.clear()
        #expect(history.items.isEmpty)
        copy("d", to: board)
        history.check()
        history.stop()
        #expect(history.items.isEmpty)
    }
}
